#!/usr/bin/env bash
# installing and quering from the nginx webserver

# Update package lists
sudo apt update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx using service command
sudo service nginx restart

# Create custom index.html file with "Hello World!" content
sudo bash -c 'echo "<!DOCTYPE html>
<html>
<head>
<title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>" > /var/www/html/index.html'

# Retrieving content Using a GET request
curl localhost
