#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me
#+is redirecting to another page.

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index
NGINX_CONF="/etc/nginx/sites-available/default"
sed -i '/server_name _;/a \    location /redirect_me
{\n        return 301 /another_page;\n    }' $NGINX_CONF
service nginx start
