#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me
#+is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | tee /var/www/html/index
NGINX_CONF="/etc/nginx/sites-available/default"
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' $NGINX_CONF
service nginx restart
