#!/usr/bin/env bash
# Configuring a server with a 404 error page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

Config_path=/etc/nginx/sites-available/default
sudo sed -i '/error_page 404/a error_page 404 /404.html;' $Config_path
sudo sed -i '/location \/ {/a location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' $Config_path
sudo service nginx restart
