#!/usr/bin/env bash
# Configuring Nginx so that its HTTP
#+ response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

Config_file=/etc/nginx/sites-available/default
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   root /var/www/html;
   index index.html;
   add_header X-Served-By '$hostname';
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > $Config_file

sudo service nginx restart
