#!/usr/bin/env bash
# Configuring Nginx so that its HTTP
#+ response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

Config_file=/etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a\\n\tadd_header X-Served-By \$hostname;' $Config_file
sudo service nginx restart
