#!/usr/bin/env bash
# Installing and Configuring a HAProxy to handle
#+ traffic between two servers

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8

sudo apt-get install haproxy=2.8.\* -y

echo "
frontend www
    bind :80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 194200-web-01 107.22.143.92:80 check
    server 194200-web-02 54.157.181.234:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
