#!/usr/bin/env bash
# Installing and Configuring a HAProxy to handle
#+ traffic between two servers

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend patrick-52-frontend
    bind :80
    mode http
    default_backend patrick-52-backend

backend patrick-52-backend
    balance roundrobin
    server 194200-web-01 107.22.143.92:80 check
    server 194200-web-02 54.157.181.234:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
