#!/usr/bin/env bash
# Installing and Configuring a HAProxy to handle
#+ traffic between two servers

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend patrick-52-frontend
    bind *:80
    mode http
    default_backend patrick-52-backend

backend patrick-52-backend
    balance roundrobin
    server 194200-web-01 100.25.2.68:80 check
    server 194200-web-02 18.210.15.42:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
