#!/usr/bin/env bash
# Configuring my server so that /redirect_me
#+is redirecting to another page permanently.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
Config_path=/etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a\\n\trewrite ^/redirect_me$ https://www.youtube.com/ permanent;' $Config_path
sudo service nginx restart
