#!/usr/bin/env bash
#Bash script that displays Best School 9 times and Hi 1 time
i=1

while [ $i -le 10 ]
do
    echo "Best school"
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    ((x++))
done
