#!/usr/bin/env bash
# configuring before.rules file to handle
#+ port forwarding

sudo ufw allow 8080
sudo sed -i '/
# rules.before
#
# Rules that should be run before the ufw command lin
# rules should be added to one of these chains:
#   ufw-before-input
#   ufw-before-output
#   ufw-before-forward
#
/a\\n
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT' /etc/ufw/before.rules

sudo disable ufw
sudo enable ufw
