#!/usr/bin/env bash
# Debugging and changing nginx user

Cnf='/etc/nginx/nginx.conf'
sed -i 's/#user www-data/user nginx/' "$Cnf"
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su -c service nginx restart nginx
