#!/usr/bin/env bash
# Debugging and changing nginx user

Cnf='/etc/nginx/nginx.conf'
sudo sed -i 's/#user www-data;/user nginx;/' "$Cnf"
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
